### ISSUE TITLE
Missing camp_pitch information

### ISSUE THREAD

**Issue by guytoronto** [giggls/osmpoidb#6]
OSM designates camp_site as the broader area, and camp_pitch as the specific spot to place a tent or caravan.

camp_pitch information is not being pulled from OSM, so it's not displaying on Open Camping Map.

**Comment by giggls** [comment]
This is not true.
Currently tourism=camp_pitch is supported as well as the now oblolete camp_site=camp_pitch tagging.

See here for an example:
https://opencampingmap.org/#18/48.64541/8.03515/1/1/bef

Can you show me a spot which is not displayed correctly? Likely this is just a database update problem. It may take a few hours for an item to be imported into poidb after it has been mapped.

**Comment by guytoronto** [comment]
I apologize! I was wrong.
It seems that the camp_pitch isn't visible unless zoomed in to level 18 or 19.
https://opencampingmap.org/#19/44.53182/-76.52373/0/1/bef

Is there a possibility of having the option to show a pitch at zoom level 16 or 17?
https://opencampingmap.org/#16/44.5312/-76.5242/1/1/bef

Also, could individual camp_pitch point/node/area information be display by clicking?
I'm cleaning up the tags for this large backcountry camp site, trying to make it more usable for other backpackers.

**Comment by giggls** [comment]
Showing pitches only in 18 and 19 is intentional as they tend to overlap otherwise.
Example:
https://opencampingmap.org/#19/48.67872/8.26153/1/1/bef

Campsite features are rendered by a special Mapserver style only in zoomlevels 18 and 19.
Code for them is at  https://github.com/giggls/campsite-features
The way they are rendered is also shown in the Open Camping Map legend.
